name: retina-databricks
channels:
  - default
  - conda-forge
dependencies:
  - python==3.7.7
  - pip==20.1.1
  - ipython==7.14.0
  - nomkl=3
  - numpy==1.18.4
  - pandas==1.0.3
  - pyarrow==1.0.1
  # pyspark loaded by the databricks runtime, so do NOT install
  - python-dateutil==2.8.1
  - pytz==2020.1
  - setuptools==58.0.4
  - six==1.15.0

