name: retina-databricks
channels:
  - default
  - conda-forge
dependencies:
  - python==3.8.12
  - pip==21.0.1
  - ipython==7.22.0
  - nomkl=3
  - numpy==1.19.2
  - pandas==1.2.4
  - pyarrow==4.0.0
  # pyspark loaded by the databricks runtime, so do NOT install
  - python-dateutil==2.8.1
  - pytz==2020.5
  - six==1.15.0

